name = "skalthoff"
main = "worker.mjs"
account_id = "506179e556e3ffb6d06e1d7486858d3e"

routes = [
  { pattern = "skalthoff.com", custom_domain = true },
  { pattern = "skalthoff.com/*", zone_name = "skalthoff.com" },

]

compatibility_date = "2025-03-10"


[site]
bucket = "./"

[observability.logs]
enabled = true